<Project>
  <PropertyGroup>
    <PackageVersion>0.1.2</PackageVersion>
    <AssemblyVersion>0.1.2.0</AssemblyVersion>
    <FileVersion>0.1.2.0</FileVersion>
    <InformationalVersion>0.1.2</InformationalVersion>
    <InformationalVersion Condition="'$(SourceRevisionId)' != ''">0.1.2+$(SourceRevisionId)</InformationalVersion>
  </PropertyGroup>
</Project>
