<Project>
  <PropertyGroup>
    <PackageVersion>0.1.4</PackageVersion>
    <AssemblyVersion>0.1.4.0</AssemblyVersion>
    <FileVersion>0.1.4.0</FileVersion>
    <InformationalVersion>0.1.4</InformationalVersion>
    <InformationalVersion Condition="'$(SourceRevisionId)' != ''">0.1.4+$(SourceRevisionId)</InformationalVersion>
  </PropertyGroup>
</Project>
