<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <TargetFrameworks Condition="$(_SdkMajor) &gt;= 9">$(TargetFrameworks);net9.0</TargetFrameworks>
    <TargetFrameworks Condition="$(_SdkMajor) &gt;= 10">$(TargetFrameworks);net10.0</TargetFrameworks>
    <AssemblyName>Lucide.NET.Blazor</AssemblyName>
    <RootNamespace>Lucide.NET.Blazor</RootNamespace>
    <PackageId>Lucide.NET.Blazor</PackageId>
    <Description>Blazor components for Lucide icons.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lucide.NET.Core\Lucide.NET.Core.csproj" />
  </ItemGroup>
</Project>
